"""Type stubs for the m3_core_rs PyO3 extension module.

Generated by hand alongside crates/m3-core-py/src/lib.rs. Keep in sync when the
binding surface changes.
"""

from typing import Optional

# --- m3-hash ---------------------------------------------------------------

def sha256_hex(text: str) -> str: ...
def sha256_hex_bytes(data: bytes) -> str: ...
def hash_provider() -> str: ...

# --- m3-vector -------------------------------------------------------------

def cosine(a: list[float], b: list[float]) -> float: ...
def cosine_batch(query: list[float], corpus: list[list[float]]) -> list[float]: ...
def mmr_rerank(
    query: list[float], candidates: list[list[float]], lambda_: float, k: int
) -> list[int]: ...
def mmr_rerank_scored(
    relevance: list[float],
    candidate_vectors: list[list[float]],
    lambda_: float,
    k: int,
    force_seed_first: bool,
) -> list[int]: ...
def enforce_displacement_guard(
    items: list[tuple[float, bool]], protected_ranks: int, margin: float
) -> list[int]: ...
def blob_as_f32(blob: bytes) -> list[float]: ...
def f32_as_blob(vec: list[float]) -> bytes: ...

# --- m3-redact -------------------------------------------------------------

class RedactionResult:
    text: str
    hits: int
    breakdown: dict[str, int]
    def __repr__(self) -> str: ...

def redact(text: str, profile: Optional[str] = ...) -> RedactionResult: ...

# --- m3-rank ---------------------------------------------------------------

class RankRow:
    id: str
    score: float
    source: str  # "fts" | "vector"
    def __init__(self, id: str, score: float, source: str) -> None: ...
    def __repr__(self) -> str: ...

def fuse(
    fts: list[RankRow],
    vector: list[RankRow],
    fts_weight: float = ...,
    vector_weight: float = ...,
) -> list[RankRow]: ...

# --- m3-route --------------------------------------------------------------

class RouteSignals:
    token_count: int
    has_entity_hint: bool
    recency_cue: bool
    intent_marker: Optional[str]
    question_form: bool
    def __repr__(self) -> str: ...

class RouteDecision:
    branch: str
    confidence: float
    signal_breakdown: list[tuple[str, float]]
    def __repr__(self) -> str: ...

def extract_signals(query: str) -> RouteSignals: ...
def decide_route(query: str, signals: RouteSignals) -> RouteDecision: ...

# --- m3-graph --------------------------------------------------------------

class GraphIndex:
    def __init__(self) -> None: ...
    def add_node(self, id: str) -> None: ...
    def add_edge(self, from_: str, to: str, kind: str, weight: float) -> None: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def neighbors_within(self, start: str, max_hops: int) -> list[tuple[str, int]]: ...
    def shortest_path(self, from_: str, to: str) -> Optional[list[str]]: ...
    def expand(self, seeds: list[str], max_hops: int, limit: int) -> list[str]: ...

class CircuitBreaker:
    def __init__(self, threshold: int, reset_after_secs: float) -> None: ...
    def state(self) -> str: ...  # "closed" | "open" | "half_open"
    def allow_request(self) -> bool: ...
    def record_success(self) -> None: ...
    def record_failure(self) -> None: ...

class RetryPolicy:
    max_attempts: int
    def __init__(
        self, max_attempts: int, base_delay_secs: float, max_delay_secs: float
    ) -> None: ...
    def delay_for_attempt(self, attempt: int) -> float: ...

# --- m3-ner-ort ------------------------------------------------------------

class Span:
    start: int
    end: int
    label: int
    score: float
    def __repr__(self) -> str: ...

def ep_priority(platform: str) -> list[str]: ...
def decode_spans(
    scores: list[float], shape: tuple[int, int, int], threshold: float
) -> list[Span]: ...

# --- m3-dispatcher + M3_* env config --------------------------------------

def estimate_tokens(text: str) -> int: ...

class DispatcherConfig:
    streams: int
    coalesce_window_ms: int
    max_batch_tokens: int
    length_buckets: list[int]
    def __init__(
        self,
        streams: Optional[int] = ...,
        coalesce_window_ms: Optional[int] = ...,
        max_batch_tokens: Optional[int] = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...

def env_config_summary() -> dict[str, object]: ...
